/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Channel
import org.openapitools.client.models.ChannelStreamInfo

import com.squareup.moshi.Json

/**
 * 
 *
 * @param channel 
 * @param streamInfo 
 */


data class ChannelPlaybackInfo (

    @Json(name = "channel")
    val channel: Channel? = null,

    @Json(name = "streamInfo")
    val streamInfo: ChannelStreamInfo? = null

)

