/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Image
import org.openapitools.client.models.Taxonomy

import com.squareup.moshi.Json

/**
 * 
 *
 * @param channelid Alpha numeric number to identify a channel. It is unique accross a territory
 * @param images 
 * @param country See Country.isoCountryCode. One channel can only belong to one country
 * @param language 
 * @param isFavourite If user marked this as a favourite
 * @param taxonomies 
 */


data class ChannelAllOf (

    /* Alpha numeric number to identify a channel. It is unique accross a territory */
    @Json(name = "channelid")
    val channelid: kotlin.String? = null,

    @Json(name = "images")
    val images: kotlin.collections.List<Image>? = null,

    /* See Country.isoCountryCode. One channel can only belong to one country */
    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "language")
    val language: kotlin.collections.List<kotlin.String>? = null,

    /* If user marked this as a favourite */
    @Json(name = "isFavourite")
    val isFavourite: kotlin.Boolean? = false,

    @Json(name = "taxonomies")
    val taxonomies: kotlin.collections.List<Taxonomy>? = null

)

