/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param streamUrl Stream URL
 * @param streamType 
 */


data class ChannelStreamInfo (

    /* Stream URL */
    @Json(name = "streamUrl")
    val streamUrl: kotlin.String? = null,

    @Json(name = "streamType")
    val streamType: ChannelStreamInfo.StreamType? = null

) {

    /**
     * 
     *
     * Values: hls,dash
     */
    enum class StreamType(val value: kotlin.String) {
        @Json(name = "hls") hls("hls"),
        @Json(name = "dash") dash("dash");
    }
}

