/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param countryIsoCode ISO 3166-1 alpha-2 code
 */


data class CountryAllOf (

    /* ISO 3166-1 alpha-2 code */
    @Json(name = "countryIsoCode")
    val countryIsoCode: kotlin.String? = null

)

