/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param languageIsoCode ISO 639-1 (3 letter code)
 */


data class LanguageAllOf (

    /* ISO 639-1 (3 letter code) */
    @Json(name = "languageIsoCode")
    val languageIsoCode: kotlin.String? = null

)

