/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Country
import org.openapitools.client.models.Language

import com.squareup.moshi.Json

/**
 * 
 *
 * @param language 
 * @param country 
 */


data class LocaleFilterAllOf (

    @Json(name = "language")
    val language: Language? = null,

    @Json(name = "country")
    val country: Country? = null

)

