/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Image

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Unique resource id
 * @param title Title of a content item
 * @param description Description of the content
 * @param url Relative URL to this resource. Ex /channel/itv1 or /taxonomy/football
 * @param taxonomyId Alpha numeric number to identify a Taxonomy. It is unique accross a territory
 * @param images 
 * @param isFavourite If user marked this as a favourite
 */


data class Taxonomy (

    /* Unique resource id */
    @Json(name = "id")
    val id: java.util.UUID? = null,

    /* Title of a content item */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Description of the content */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Relative URL to this resource. Ex /channel/itv1 or /taxonomy/football */
    @Json(name = "url")
    val url: kotlin.String? = null,

    /* Alpha numeric number to identify a Taxonomy. It is unique accross a territory */
    @Json(name = "taxonomyId")
    val taxonomyId: kotlin.String? = null,

    @Json(name = "images")
    val images: kotlin.collections.List<Image>? = null,

    /* If user marked this as a favourite */
    @Json(name = "isFavourite")
    val isFavourite: kotlin.Boolean? = false

)

