/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Image

import com.squareup.moshi.Json

/**
 * 
 *
 * @param taxonomyId Alpha numeric number to identify a Taxonomy. It is unique accross a territory
 * @param images 
 * @param isFavourite If user marked this as a favourite
 */


data class TaxonomyAllOf (

    /* Alpha numeric number to identify a Taxonomy. It is unique accross a territory */
    @Json(name = "taxonomyId")
    val taxonomyId: kotlin.String? = null,

    @Json(name = "images")
    val images: kotlin.collections.List<Image>? = null,

    /* If user marked this as a favourite */
    @Json(name = "isFavourite")
    val isFavourite: kotlin.Boolean? = false

)

